networks:
  realtime-chat:

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: realtime-chat
    ports:
      - 3306:3306
    networks:
      - realtime-chat
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - realtime-chat
