# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# https://docs.soketi.app/

networks:
  realtime-chat:

services:
  soketi:
    container_name: soketi
    networks:
      - realtime-chat
    ports:
    - published: 6001
      target: 6001
    - published: 9601
      target: 9601
    image: quay.io/soketi/soketi:1.0-16-debian
    env_file: ./.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: realtime-chat
    ports:
      - 3306:3306
    networks:
      - realtime-chat
    volumes:
    - /var/docker-containers-data/mysql_data:/var/lib/mysql