# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# https://docs.soketi.app/

networks:
  soketi:
    name: "soketi"

services:
  soketi:
    container_name: soketi
    ports:
    - published: 6001
      target: 6001
    - published: 9601
      target: 9601
    image: quay.io/soketi/soketi:1.0-16-debian
    env_file: ./.env