apiVersion: apps/v1
kind: Deployment
metadata:
  name: soketi
  labels:
    app: soketi
spec:
  replicas: 1
  template:
    metadata:
      name: soketi
      labels:
        app: soketi
    spec:
      containers:
        - name: soketi
          image: quay.io/soketi/soketi:1.0-16-debian
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6001
              hostPort: 6001
              name: api
            - containerPort: 9601
              hostPort: 9601
              name: metrics
          envFrom:
            - secretRef:
                name: soketi-secret
                optional: false
      restartPolicy: Always
  selector:
    matchLabels:
      app: soketi
