apiVersion: v1
kind: Service
metadata:
  name: soketi
spec:
  selector:
    app: soketi
  ports:
    - name: api
      port: 6001
      targetPort: 6001

    - name: metrics
      port: 9601
      targetPort: 9601


  type: LoadBalancer